### PR TITLE
add DoH3

### PR DESCRIPTION
**Pull request by hellodword**
As @ainar-g [said](https://github.com/AdguardTeam/AdGuardHome/issues/3955#issuecomment-997836595), 

> AFAIK, the Go standard library currently doesn't support HTTP/3, and probably won't until it graduates the draft standard phase. Once it does, the Go standard library will probably get an implementation shortly.

but it seems that go team will not implement it very soon. [^1] [^2]

And I noticed that the `dnsproxy` is using `quic-go` for QUIC, and `quic-go` has a [HTTP/3 implementation](https://github.com/lucas-clemente/quic-go/tree/master/http3), so why not support it now? We can switch to the Go standard library once it has a implementation.

@ameshkov 

[^1]: https://github.com/golang/go/issues/44886
[^2]: https://github.com/golang/go/issues/32204

### CODE REVIEW

**Comment by hellodword** [comment]
@ainar-g How do you think about this?

**Comment by ameshkov** [comment]
Generally, it's not bad, we'll consider the PR, thank you!

**Comment by iJorgen** [comment]
Any estimate when HTTP/3 upstream will be added? This month, this quarter, this year, next year? Fully understand your primary focus is on AdGuard Home right now, but would be so cool to use DNSproxy with all "next-gen" DNS-protocols.

PS. Just noticed DNSCrypt released HTTP/3 support a few days ago as a teaser... ;-)

**Comment by ameshkov** [comment]
Added here:
https://github.com/AdguardTeam/dnsproxy/commit/823fa92f99c4bf1093bc922d4f47ff2f94314781

After all, we decided not to make a separate Upstream for DOH3 and extend the existing one.

**Pull request closed without merging**
