### PR TITLE
DNS-over-QUIC: always use 2-byte prefix for DNS message

### PR DESCRIPTION
**Pull request by libor-peltan-cznic**

### CODE REVIEW

**Comment by ameshkov** [comment]
@libor-peltan-cznic could you please explain why do we need it?

**Comment by libor-peltan-cznic** [comment]
This is according to latest specification https://www.ietf.org/archive/id/draft-ietf-dprive-dnsoquic-11.html#section-5.2 (which will, I hope, become RFC soon). The target is interoperability with other implementations, which work according to the same standard.

**Comment by ameshkov** [comment]
Oh my, this was an unexpected breaking change.

Thank you for letting us know. We'll implement the fix on our side, but it will be more complicated. We still need to support older clients that don't write any prefix.

**Comment by libor-peltan-cznic** [comment]
Perfect, I will be happy with any kind of fix. Anyway, I'm a noob in Go, so I would be happy if anyone better writes the code. Thank you!

Anyway, there are still some other issues, I think, but I had little time to explore them in detail:
1) larger DNS response may arrive in multiple packets (according to MTU), which seemingly requires to call `stream.Read()` multiple times
2) some kinds of DNS responses (e.g. AXFR) consist of multiple DNS messages: 2-byte-prefix + 1st-message + 2-byte-prefix + 2nd-message ... This seems to not be supported by your DNS proxy. (This is obviously forbidden for DNS-over-UDP, but TCP and QUIC are OK.)

**Comment by ameshkov** [comment]
> larger DNS response may arrive in multiple packets

Tbh , this is unexpected as I think it's supposed to be handled on the QUIC level.

Thanks for the info!

**Comment by GAMEZs9** [comment]
> #229

**Comment by libor-peltan-cznic** [comment]
> > larger DNS response may arrive in multiple packets
> 
> Tbh , this is unexpected as I think it's supposed to be handled on the QUIC level.

You are right, sorry for that. Stream handles this and Read method reads it whole, regardless of fragmentation of data into multiple packets. But point 2 remains.

**Pull request closed without merging**
