### PR TITLE
Make IPv6 addresses prioritized over IPv4 ones.

### PR DESCRIPTION
**Pull request by zaczh**
IPv6 is wildly used now. Modern operating systems already take IPv6 addresses over IPv4 ones.

### CODE REVIEW

**Review by ameshkov — CHANGES_REQUESTED** [review]
This one is debatable. In reality, most of the networks are IPv4-only and prioritizing IPv6 without additional checks may lead to unexpected results. For instance, I've seen networks where IPv6 is dropped instead of failing immediately with `unknown route to host`.

The algorithm need to be smarter if we want to prioritize IPv6. Or we could make it configurable for now.

**Comment by zaczh** [comment]
> This one is debatable. In reality, most of the networks are IPv4-only and prioritizing IPv6 without additional checks may lead to unexpected results. For instance, I've seen networks where IPv6 is dropped instead of failing immediately with `unknown route to host`.
> 
> The algorithm need to be smarter if we want to prioritize IPv6. Or we could make it configurable for now.

You mean IPv6 socket is successfully built but sending packets via it fails? IMHO I don't see any network have this behavior. Nevertheless I have searched this repository and find that v4/v6 fallback may have already been supported. Specifically, the _dial_ function in client.go handles TLS/QUIC handshake and check if it is successful.

```
func (c *client) dial(ctx context.Context) error {
	c.logger.Infof("Starting new connection to %s (%s -> %s), source connection ID %s, destination connection ID %s, version %s", c.tlsConf.ServerName, c.sconn.LocalAddr(), c.sconn.RemoteAddr(), c.srcConnID, c.destConnID, c.version)

	c.conn = newClientConnection(
		c.sconn,
		c.packetHandlers,
		c.destConnID,
		c.srcConnID,
		c.config,
		c.tlsConf,
		c.initialPacketNumber,
		c.use0RTT,
		c.hasNegotiatedVersion,
		c.tracer,
		c.tracingID,
		c.logger,
		c.version,
	)
	c.packetHandlers.Add(c.srcConnID, c.conn)

	errorChan := make(chan error, 1)
	go func() {
		err := c.conn.run() // returns as soon as the connection is closed

		if e := (&errCloseForRecreating{}); !errors.As(err, &e) && c.createdPacketConn {
			c.packetHandlers.Destroy()
		}
		errorChan <- err
	}()

	// only set when we're using 0-RTT
	// Otherwise, earlyConnChan will be nil. Receiving from a nil chan blocks forever.
	var earlyConnChan <-chan struct{}
	if c.use0RTT {
		earlyConnChan = c.conn.earlyConnReady()
	}

	select {
	case <-ctx.Done():
		c.conn.shutdown()
		return ctx.Err()
	case err := <-errorChan:
		var recreateErr *errCloseForRecreating
		if errors.As(err, &recreateErr) {
			c.initialPacketNumber = recreateErr.nextPacketNumber
			c.version = recreateErr.nextVersion
			c.hasNegotiatedVersion = true
			return c.dial(ctx)
		}
		return err
	case <-earlyConnChan:
		// ready to send 0-RTT data
		return nil
	case <-c.conn.HandshakeComplete().Done():
		// handshake successfully completed
		return nil
	}
}
```
So my opinion is that even though we prioritize IPv6 address but it fails, we still have IPv4 connectivity. But for now I don't see test cases related to this v4/v6 fallback.

**Comment by ameshkov** [comment]
> You mean IPv6 socket is successfully built but sending packets via it fails?

Not just fails, I mean I've seen cases when packets sent through a seemingly valid IPv6 interface were dropped, i.e. the connections were timing out. "Attempt to connect to IPv6 first, then IPv4" approach will be problematic in these cases.

Check how Chrome does that:
https://codereview.chromium.org/7029049

We have two reliable options:
1. Simple one: introduce a configuration parameter for those who needs IPv6 to be preferred.
2. A more complicated one: modify the `dial` in `bootstrap.go` and run two connections in parallel (maybe prefer IPv6 a little bit over IPv4). Just like what Chrome does.

**Comment by zaczh** [comment]
> We have two reliable options:
> 
> 1. Simple one: introduce a configuration parameter for those who needs IPv6 to be preferred.
> 2. A more complicated one: modify the `dial` in `bootstrap.go` and run two connections in parallel (maybe prefer IPv6 a little bit over IPv4). Just like what Chrome does.
I prefer the second one. But I can not finish this job yet. Maybe I can submit a new PR when I'm ready. So I am closing this. Thank you.

**Pull request closed without merging**
