### PR TITLE
Enhance Docker Image

### PR DESCRIPTION
**Pull request by salevdns**
Add default config.yaml + default CMD to Docker Image to help users kickstart their deployment.
(https://github.com/AdguardTeam/dnsproxy/issues/208#issuecomment-1649940232)

Unfortunate timing on my end (ff8022f) . For what it's worth, here is my unadapted WIP Dockerfile that I was preparing to contribute:
Maybe someone can still cherry-pick something useful from it.
```Dockerfile
FROM alpine AS prep

ARG VERSION DIST_DIR TARGETARCH TARGETOS

WORKDIR /opt/dnsproxy
RUN apk add --no-cache ca-certificates libcap
RUN wget -qO- https://github.com/AdguardTeam/dnsproxy/releases/download/${VERSION}/dnsproxy-${TARGETOS}-${TARGETARCH}-${VERSION}.tar.gz | tar -zxf - --strip-components 2 ./${TARGETOS}-${TARGETARCH}/dnsproxy &&\
      setcap 'cap_net_bind_service=+eip' dnsproxy &&\
      wget -qO config.yaml https://raw.githubusercontent.com/AdguardTeam/dnsproxy/master/config.yaml.dist

FROM scratch
ARG USER_ID=5533 BUILD_DATE VERSION VCS_REF

LABEL \
  maintainer="AdGuard Team <devteam@adguard.com>" \
  org.opencontainers.image.authors="AdGuard Team <devteam@adguard.com>" \
  org.opencontainers.image.created=${BUILD_DATE} \
  org.opencontainers.image.description="Simple DNS proxy with DoH, DoT, DoQ and DNSCrypt support" \
  org.opencontainers.image.documentation="https://github.com/AdguardTeam/dnsproxy#usage" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.revision=${VCS_REF} \
  org.opencontainers.image.source="https://github.com/AdguardTeam/dnsproxy" \
  org.opencontainers.image.title="DNS Proxy" \
  org.opencontainers.image.url="https://github.com/AdguardTeam/dnsproxy" \
  org.opencontainers.image.vendor="AdGuard" \
  org.opencontainers.image.version=${VERSION}

WORKDIR /opt/dnsproxy
COPY --from=prep /opt/dnsproxy .
COPY --from=prep /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 53/tcp 53/udp 443/tcp 443/udp 853/tcp 853/udp 5443/tcp 5443/udp 6060/tcp
USER ${USER_ID}:${USER_ID}
ENTRYPOINT ["/opt/dnsproxy/dnsproxy"]
CMD ["--config-path=/opt/dnsproxy/config.yaml"]
```

### CODE REVIEW

**Comment by ameshkov** [comment]
Hi @salevdns!

It would be better to create an issue first and discuss it there. If we decide to proceed with it, then it's time to open a new PR.

To be honest, I am not entirely sure we should supply a configuration file. If we do, people will be required to use the config file with the docker image and dnsproxy allows running with command-line arguments. It's subjective, but in some cases I prefer to stick to command-line arguments only.

**Comment by salevdns** [comment]
Hello @ameshkov,

I appreciate your concern, but it seems to be invalid. When specifying command-line arguments as part of the `docker run`, they will actually replace the CMD command specified in the Dockerfile, allowing us to have both options available.

**Comment by ameshkov** [comment]
Oh, makes sense. Could you please reopen the PR?

**Comment by salevdns** [comment]
Thanks for your consideration!
It seems like I don't have the permissions to reopen this PR.
I squashed and force pushed right after you closed the issue but have now reverted the branch to [e551957](https://github.com/AdguardTeam/dnsproxy/pull/344/commits/e551957f82a3ea616ab09b9bd2da0682e8e74895).
Maybe you can reopen it now, and then I can squash my commits again.

**Comment by salevdns** [comment]
Okay, should be fine now.

**Pull request closed without merging**
